In [1]:
from geopy.geocoders import Nominatim
import pandas as pd

In [2]:
def get_lat_long(address):
    geolocator = Nominatim(user_agent="Get_Geo_Codes")
    location = geolocator.geocode(address)
    if location is not None:
        lat_ =location.latitude
        long_ = location.longitude
    else:
        lat_ =long_ = None
        
    return lat_,long_

In [3]:
all_df = pd.read_csv('../data/combine_3_cities.csv')

In [4]:
lat =[]
long=[]
for index,data in all_df.iterrows():
    address = f'{data["Neighbourhood"]} {data["City"]} {data["Country"]}'
    lat_ , long_ =get_lat_long(address)
    lat.append(lat_)
    long.append(long_)

In [5]:
all_df['Latitude']=lat
all_df['Longitude']=long

## checking Missing Values in Lat and Long

In [7]:
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Neighbourhood  167 non-null    object
 1   City           167 non-null    object
 2   Country        167 non-null    object
 3   Latitude       101 non-null    float64
 4   Longitude      101 non-null    float64
dtypes: float64(2), object(3)
memory usage: 6.6+ KB

## Getting some of the missing *values*

In [8]:
for index , data in all_df[(all_df.Latitude.isna())].iterrows():
    address = f'{data["Neighbourhood"]},{data["Country"]}'
    lat_ , long_ =get_lat_long(address)
    all_df.loc[all_df['Neighbourhood']==data['Neighbourhood'],'Latitude']=lat_
    all_df.loc[all_df['Neighbourhood']==data['Neighbourhood'],'Longitude']=long_
    print('The geograpical coordinate of {} are {}, {}.'.format(address, lat_, long_))

The geograpical coordinate of Anders Park East,Canada are None, None.
The geograpical coordinate of Anders South,Canada are None, None.
The geograpical coordinate of Bower Ponds Recreation Area,Canada are None, None.
The geograpical coordinate of Chiles Industrial Park,Canada are None, None.
The geograpical coordinate of Clearview Extension,Canada are None, None.
The geograpical coordinate of Clearview Meadows,Canada are 44.42721985, -80.09508624311499.
The geograpical coordinate of Clearview Ridge,Canada are 47.5298986, -52.8744254.
The geograpical coordinate of Deer Park Estates,Canada are 43.182807, -79.5305904.
The geograpical coordinate of Deer Park Village,Canada are 49.2433101, -123.0031696.
The geograpical coordinate of East Burnt Lake,Canada are None, None.
The geograpical coordinate of Edgar Industrial Park,Canada are None, None.
The geograpical coordinate of Gaetz Lakes Sanctuary,Canada are None, None.
The geograpical coordinate of Glendale Park Estates,Canada are None, None.
The geograpical coordinate of Highland Green Estates,Canada are None, None.
The geograpical coordinate of Johnstone Crossing,Canada are None, None.
The geograpical coordinate of Johnstone Park,Canada are 43.702106, -79.80893430879999.
The geograpical coordinate of Kentwood East,Canada are None, None.
The geograpical coordinate of Lancaster Meadows,Canada are 45.3986334, -75.6107363.
The geograpical coordinate of Laredo,Canada are 52.816871, -128.74440596746703.
The geograpical coordinate of Lonsdale,Canada are 44.2753616, -77.1266681.
The geograpical coordinate of McKenzie Trail Recreation Area,Canada are None, None.
The geograpical coordinate of Michener Hill,Canada are None, None.
The geograpical coordinate of Morrisroe,Canada are None, None.
The geograpical coordinate of Morrisroe Extension,Canada are None, None.
The geograpical coordinate of Northlands Industrial Park,Canada are None, None.
The geograpical coordinate of Oriole Park West,Canada are 49.8473909, -119.67407083496933.
The geograpical coordinate of Parkvale,Canada are 44.6408571, -63.7132251.
The geograpical coordinate of Red Deer Golf and Country Club,Canada are None, None.
The geograpical coordinate of Riverside Light Industrial Park,Canada are None, None.
The geograpical coordinate of Riverside Meadows,Canada are None, None.
The geograpical coordinate of Rosedale Meadows,Canada are None, None.
The geograpical coordinate of South Hill,Canada are 43.6779261, -79.4057671.
The geograpical coordinate of Southpointe Junction,Canada are None, None.
The geograpical coordinate of Sunnybrook Extension,Canada are None, None.
The geograpical coordinate of Three Mile Bend Recreation Area,Canada are None, None.
The geograpical coordinate of Vanier Woods East,Canada are None, None.
The geograpical coordinate of West Burnt Lake,Canada are None, None.
The geograpical coordinate of West QE2,Canada are None, None.
The geograpical coordinate of Woodlea,Canada are 45.3205386, -75.78500059820267.
The geograpical coordinate of U.S. NAVAL BASE,United States are 41.343636950000004, -72.09348643841241.
The geograpical coordinate of OLD AURORA,United States are 38.9297545, -111.928811.
The geograpical coordinate of B. W. COOPER,United States are 34.165842, -94.311735.
The geograpical coordinate of MARLYVILLE - FONTAINEBLEAU,United States are None, None.
The geograpical coordinate of GERT TOWN,United States are 42.7216108, -73.8273267.
The geograpical coordinate of ST. CLAUDE,United States are 35.1081103, -101.362741.
The geograpical coordinate of CENTRAL BUSINESS DISTRICT,United States are 40.4404399, -80.0058066.
The geograpical coordinate of CENTRAL CITY,United States are 42.2039609, -91.5243615.
The geograpical coordinate of VILLAGE DE LEST,United States are None, None.
The geograpical coordinate of VIAVANT - VENETIAN ISLES,United States are None, None.
The geograpical coordinate of NEW AURORA - ENGLISH TURN,United States are None, None.
The geograpical coordinate of TALL TIMBERS - BRECHTEL,United States are None, None.
The geograpical coordinate of FISCHER DEV,United States are None, None.
The geograpical coordinate of ST. THOMAS DEV,United States are None, None.
The geograpical coordinate of EAST RIVERSIDE,United States are 39.9317421, -79.9272735.
The geograpical coordinate of WEST RIVERSIDE,United States are 35.6697932, -85.7852597.
The geograpical coordinate of EAST CARROLLTON,United States are 33.59633545, -85.04473235745387.
The geograpical coordinate of TULANE - GRAVIER,United States are None, None.
The geograpical coordinate of TREME - LAFITTE,United States are None, None.
The geograpical coordinate of LAKESHORE - LAKE VISTA,United States are 28.5645594, -81.533585.
The geograpical coordinate of ST. BERNARD AREA,United States are None, None.
The geograpical coordinate of ST. ANTHONY,United States are 45.0283001, -93.2187368.
The geograpical coordinate of LAKE TERRACE & OAKS,United States are 32.479658, -86.36752.
The geograpical coordinate of DESIRE AREA,United States are 47.4463904, -122.10806701778826.
The geograpical coordinate of FLORIDA AREA,United States are 26.14220995, -81.56170378849319.
The geograpical coordinate of FLORIDA DEV,United States are None, None.
The geograpical coordinate of WEST LAKE FOREST,United States are 42.2219684, -87.8731256.

In [9]:
all_df.isnull().sum()

Neighbourhood     0
City              0
Country           0
Latitude         38
Longitude        38
dtype: int64

In [10]:
for index , data in all_df[(all_df.Latitude.isna())].iterrows():
    address = f'{data["Neighbourhood"]}'
    lat_ , long_ =get_lat_long(address)
    all_df.loc[all_df['Neighbourhood']==data['Neighbourhood'],'Latitude']=lat_
    all_df.loc[all_df['Neighbourhood']==data['Neighbourhood'],'Longitude']=long_
    print('The geograpical coordinate of {} are {}, {}.'.format(address, lat_, long_))

The geograpical coordinate of Anders Park East are None, None.
The geograpical coordinate of Anders South are 53.2165798, 6.5968342.
The geograpical coordinate of Bower Ponds Recreation Area are None, None.
The geograpical coordinate of Chiles Industrial Park are None, None.
The geograpical coordinate of Clearview Extension are 40.6374206, -80.06520561382794.
The geograpical coordinate of East Burnt Lake are 42.1302964, -120.1995728.
The geograpical coordinate of Edgar Industrial Park are 52.308964849999995, -113.84309114313757.
The geograpical coordinate of Gaetz Lakes Sanctuary are None, None.
The geograpical coordinate of Glendale Park Estates are 33.5399262, -112.24182025956823.
The geograpical coordinate of Highland Green Estates are 30.532227, -91.103417.
The geograpical coordinate of Johnstone Crossing are -27.6159465, 152.7473888.
The geograpical coordinate of Kentwood East are 35.95839135, -83.58300917104935.
The geograpical coordinate of McKenzie Trail Recreation Area are None, None.
The geograpical coordinate of Michener Hill are 40.0787377, -75.1737223.
The geograpical coordinate of Morrisroe are 34.133236249999996, -118.12765995095523.
The geograpical coordinate of Morrisroe Extension are None, None.
The geograpical coordinate of Northlands Industrial Park are None, None.
The geograpical coordinate of Red Deer Golf and Country Club are None, None.
The geograpical coordinate of Riverside Light Industrial Park are None, None.
The geograpical coordinate of Riverside Meadows are 30.226784199999997, -97.7007459256202.
The geograpical coordinate of Rosedale Meadows are 42.357584200000005, -83.35698536292085.
The geograpical coordinate of Southpointe Junction are None, None.
The geograpical coordinate of Sunnybrook Extension are None, None.
The geograpical coordinate of Three Mile Bend Recreation Area are None, None.
The geograpical coordinate of Vanier Woods East are None, None.
The geograpical coordinate of West Burnt Lake are 67.53166039999999, -133.563333598436.
The geograpical coordinate of West QE2 are 51.0569976, -1.3152342011314975.
The geograpical coordinate of MARLYVILLE - FONTAINEBLEAU are None, None.
The geograpical coordinate of VILLAGE DE LEST are 47.6728754, -3.2088833.
The geograpical coordinate of VIAVANT - VENETIAN ISLES are None, None.
The geograpical coordinate of NEW AURORA - ENGLISH TURN are None, None.
The geograpical coordinate of TALL TIMBERS - BRECHTEL are None, None.
The geograpical coordinate of FISCHER DEV are None, None.
The geograpical coordinate of ST. THOMAS DEV are 50.7168857, -3.5418527.
The geograpical coordinate of TULANE - GRAVIER are None, None.
The geograpical coordinate of TREME - LAFITTE are 29.9622979, -90.0720362.
The geograpical coordinate of ST. BERNARD AREA are -41.2042257, 146.8194449.
The geograpical coordinate of FLORIDA DEV are 29.639504950000003, -82.42044737532613.

In [11]:
all_df.isnull().sum()

Neighbourhood     0
City              0
Country           0
Latitude         19
Longitude        19
dtype: int64

In [12]:
all_df[all_df.Latitude.isna()]

,Neighbourhood,City,Country,Latitude,Longitude
13,Anders Park East,Alberta,Canada,NaN,NaN
17,Bower Ponds Recreation Area,Alberta,Canada,NaN,NaN
19,Chiles Industrial Park,Alberta,Canada,NaN,NaN
35,Gaetz Lakes Sanctuary,Alberta,Canada,NaN,NaN
56,McKenzie Trail Recreation Area,Alberta,Canada,NaN,NaN
59,Morrisroe Extension,Alberta,Canada,NaN,NaN
62,Northlands Industrial Park,Alberta,Canada,NaN,NaN
69,Red Deer Golf and Country Club,Alberta,Canada,NaN,NaN
72,Riverside Light Industrial Park,Alberta,Canada,NaN,NaN
78,Southpointe Junction,Alberta,Canada,NaN,NaN
80,Sunnybrook Extension,Alberta,Canada,NaN,NaN
81,Three Mile Bend Recreation Area,Alberta,Canada,NaN,NaN
86,Vanier Woods East,Alberta,Canada,NaN,NaN
105,MARLYVILLE - FONTAINEBLEAU,New Orleans,United States,NaN,NaN
114,VIAVANT - VENETIAN ISLES,New Orleans,United States,NaN,NaN
115,NEW AURORA - ENGLISH TURN,New Orleans,United States,NaN,NaN
116,TALL TIMBERS - BRECHTEL,New Orleans,United States,NaN,NaN
117,FISCHER DEV,New Orleans,United States,NaN,NaN
132,TULANE - GRAVIER,New Orleans,United States,NaN,NaN

In [13]:
all_df.loc[all_df['Neighbourhood'] == 'Bower Ponds Recreation Area', 'Latitude'] = 52.2688
all_df.loc[all_df['Neighbourhood'] == 'Bower Ponds Recreation Area', 'Longitude'] = -113.8314

all_df.loc[all_df['Neighbourhood'] == 'Gaetz Lakes Sanctuary', 'Latitude'] = 52.2849
all_df.loc[all_df['Neighbourhood'] == 'Gaetz Lakes Sanctuary', 'Longitude'] = -113.7954

all_df.loc[all_df['Neighbourhood'] == 'Morrisroe Extension', 'Latitude'] = 52.2558
all_df.loc[all_df['Neighbourhood'] == 'Morrisroe Extension', 'Longitude'] = -113.7777

all_df.loc[all_df['Neighbourhood'] == 'Red Deer Golf and Country Club', 'Latitude'] = 52.2635
all_df.loc[all_df['Neighbourhood'] == 'Red Deer Golf and Country Club', 'Longitude'] = -113.8400

all_df.loc[all_df['Neighbourhood'] == 'Sunnybrook Extension', 'Latitude'] = 43.7228
all_df.loc[all_df['Neighbourhood'] == 'Sunnybrook Extension', 'Longitude'] = -79.3729

all_df.loc[all_df['Neighbourhood'] == 'Three Mile Bend Recreation Area', 'Latitude'] = 52.3019
all_df.loc[all_df['Neighbourhood'] == 'Three Mile Bend Recreation Area', 'Longitude'] = -113.7817

all_df.loc[all_df['Neighbourhood'] == 'MARLYVILLE - FONTAINEBLEAU', 'Latitude'] = 29.9523
all_df.loc[all_df['Neighbourhood'] == 'MARLYVILLE - FONTAINEBLEAU', 'Longitude'] = -90.1132

all_df.loc[all_df['Neighbourhood'] == 'VIAVANT - VENETIAN ISLES', 'Latitude'] = 30.0178
all_df.loc[all_df['Neighbourhood'] == 'VIAVANT - VENETIAN ISLES', 'Longitude'] = -89.9395

all_df.loc[all_df['Neighbourhood'] == 'TALL TIMBERS - BRECHTEL', 'Latitude'] = 29.9049
all_df.loc[all_df['Neighbourhood'] == 'TALL TIMBERS - BRECHTEL', 'Longitude'] = -89.9976

all_df.loc[all_df['Neighbourhood'] == 'FISCHER DEV', 'Latitude'] = 29.93239931
all_df.loc[all_df['Neighbourhood'] == 'FISCHER DEV', 'Longitude'] = -90.04154205

all_df.loc[all_df['Neighbourhood'] == 'TULANE - GRAVIER', 'Latitude'] = 29.9592
all_df.loc[all_df['Neighbourhood'] == 'TULANE - GRAVIER', 'Longitude'] = -90.0849

all_df.loc[all_df['Neighbourhood'] == 'NEW AURORA - ENGLISH TURN', 'Latitude'] = 44.8408158
all_df.loc[all_df['Neighbourhood'] == 'NEW AURORA - ENGLISH TURN', 'Longitude'] = -93.5191807

all_df.loc[all_df['Neighbourhood'] == 'Riverside Light Industrial Park', 'Latitude'] = 25.04456915
all_df.loc[all_df['Neighbourhood'] == 'Riverside Light Industrial Park', 'Longitude'] = -77.3314679919205

all_df.loc[all_df['Neighbourhood'] == 'McKenzie Trail Recreation Area', 'Latitude'] = 48.1047453
all_df.loc[all_df['Neighbourhood'] == 'McKenzie Trail Recreation Area', 'Longitude'] = -103.1035193

In [15]:
nan = all_df[all_df.Latitude.isna()]

In [16]:
nan.index

Index([13, 19, 62, 78, 86], dtype='int64')

In [18]:
all_df.drop(nan.index,inplace=True)

In [19]:
all_df[all_df.Latitude.isna()]

Empty DataFrame
Columns: [Neighbourhood, City, Country, Latitude, Longitude]
Index: []

In [20]:
all_df

,Neighbourhood,City,Country,Latitude,Longitude
0,Charlottenburg-Wilmersdorf,Berlin,Germany,52.507856,13.263952
1,Friedrichshain-Kreuzberg,Berlin,Germany,52.501115,13.444285
2,Lichtenberg,Berlin,Germany,52.532161,13.511893
3,Marzahn-Hellersdorf,Berlin,Germany,52.522523,13.587663
4,Mitte,Berlin,Germany,52.517885,13.404060
...,...,...,...,...,...
162,READ BLVD EAST,New Orleans,United States,30.031682,-89.975295
163,WEST LAKE FOREST,New Orleans,United States,42.221968,-87.873126
164,LITTLE WOODS,New Orleans,United States,30.075200,-89.944235
165,FAIRGROUNDS,New Orleans,United States,29.983767,-90.081270
166,IBERVILLE,New Orleans,United States,29.981962,-90.109340

In [21]:
all_df.to_csv('../data/df_with_lat_long.csv',index=False)